---
# ============================================
# iptables Persistence Tasks
# ============================================
# Saves iptables rules to survive reboots

- name: Save iptables rules to ensure persistence across reboots
  ansible.builtin.shell: "{{ item }}"
  loop:
    - iptables-save > /etc/iptables/rules.v4
    - ip6tables-save > /etc/iptables/rules.v6
  become: yes
  changed_when: true
